In [60]:
import tensorflow as tf
from tensorflow.keras.layers import Lambda
from keras import backend
from keras.losses import binary_crossentropy
from keras import backend as K
import keras

In [107]:
def custom_loss(weight_ratio):
    def loss(y_true, y_pred):
        when_y_1 = y_true*tf.keras.backend.log(y_pred)*(1/weight_ratio)
        # when_y_1 = y_true*tf.keras.backend.log(y_pred)*(1/1)
        neg_y_pred = Lambda(lambda x: -x)(y_pred)
        when_y_0 = ( 1+Lambda(lambda x: -x)(y_true))*tf.keras.backend.log(1+neg_y_pred )

        weighted_cross_entr = Lambda(lambda x: -x)(when_y_0+when_y_1)
        return tf.keras.backend.mean(weighted_cross_entr)
    return loss


In [108]:
p = [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
q = [0.8, 0.9, 0.9, 0.6, 0.8, 0.1, 0.4, 0.2, 0.1, 0.3]

In [109]:
y_true = backend.variable(p)

In [110]:
y_pred = backend.variable(q)

In [111]:
mean_ce = backend.eval(binary_crossentropy(y_true, y_pred))


In [115]:
print('Average Cross Entropy: %.5f nats' % mean_ce)

Average Cross Entropy: 0.24692 nats


In [120]:
l = custom_loss(3)

In [121]:
l(y_true, y_pred)

The following Variables were used a Lambda layer's call (lambda_51), but
are not present in its tracked objects:
  <tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=array([0.8, 0.9, 0.9, 0.6, 0.8, 0.1, 0.4, 0.2, 0.1, 0.3], dtype=float32)>
It is possible that this is intended behavior, but it is more likely
an omission. This is a strong indication that this layer should be
formulated as a subclassed Layer rather than a Lambda layer.
The following Variables were used a Lambda layer's call (lambda_52), but
are not present in its tracked objects:
  <tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0.], dtype=float32)>
It is possible that this is intended behavior, but it is more likely
an omission. This is a strong indication that this layer should be
formulated as a subclassed Layer rather than a Lambda layer.


<tf.Tensor: shape=(), dtype=float32, numpy=0.16906431>

In [122]:
l(y_true, y_pred)

The following Variables were used a Lambda layer's call (lambda_54), but
are not present in its tracked objects:
  <tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=array([0.8, 0.9, 0.9, 0.6, 0.8, 0.1, 0.4, 0.2, 0.1, 0.3], dtype=float32)>
It is possible that this is intended behavior, but it is more likely
an omission. This is a strong indication that this layer should be
formulated as a subclassed Layer rather than a Lambda layer.
The following Variables were used a Lambda layer's call (lambda_55), but
are not present in its tracked objects:
  <tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0.], dtype=float32)>
It is possible that this is intended behavior, but it is more likely
an omission. This is a strong indication that this layer should be
formulated as a subclassed Layer rather than a Lambda layer.


<tf.Tensor: shape=(), dtype=float32, numpy=0.16906431>

In [123]:
sum(l(y_true, y_pred))/10

The following Variables were used a Lambda layer's call (lambda_57), but
are not present in its tracked objects:
  <tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=array([0.8, 0.9, 0.9, 0.6, 0.8, 0.1, 0.4, 0.2, 0.1, 0.3], dtype=float32)>
It is possible that this is intended behavior, but it is more likely
an omission. This is a strong indication that this layer should be
formulated as a subclassed Layer rather than a Lambda layer.
The following Variables were used a Lambda layer's call (lambda_58), but
are not present in its tracked objects:
  <tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0.], dtype=float32)>
It is possible that this is intended behavior, but it is more likely
an omission. This is a strong indication that this layer should be
formulated as a subclassed Layer rather than a Lambda layer.


TypeError: Cannot iterate over a scalar tensor.

In [69]:
def weighted_bce(y_true, y_pred):
    weights =5
    bce = K.binary_crossentropy(y_true, y_pred)
    weighted_bce = K.mean(bce * weights)
    return weighted_bce

In [70]:
weighted_bce(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=1.2345986>

https://machinelearningmastery.com/cross-entropy-for-machine-learning/

In [71]:
    bce = K.binary_crossentropy(y_true, y_pred)


In [73]:
loss =keras.losses.BinaryCrossentropy()

In [80]:
loss(y_true,y_pred,
    sample_weight =4)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9876789>