In [25]:
import os
import tensorflow as tf
from tensorflow import keras

# from config import hyparams, exp
from tensorflow.keras.layers import Lambda

In [40]:
def custom_loss(weight_ratio):
    """
    Note that weight_ratio is postive/negative
    """
    def loss(y_true, y_pred):
        when_y_1 = y_true*tf.keras.backend.log(y_pred)*(1/weight_ratio)
        # when_y_1 = y_true*tf.keras.backend.log(y_pred)*(1/1)
        neg_y_pred = Lambda(lambda x: -x)(y_pred)
        when_y_0 = ( 1+Lambda(lambda x: -x)(y_true))*tf.keras.backend.log(1+neg_y_pred )

        weighted_cross_entr = Lambda(lambda x: -x)(when_y_0+when_y_1)
        return weighted_cross_entr
    return loss


In [41]:
y_true = tf.constant([1., 0.,1., 1.])
y_pred = tf.constant([0.9,.1,.7, .8])

In [42]:
loss = custom_loss(3)

In [43]:
loss(y_true, y_pred)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.03512018, 0.10536055, 0.11889166, 0.07438118], dtype=float32)>

In [44]:
sum(loss(y_true, y_pred))

<tf.Tensor: shape=(), dtype=float32, numpy=0.33375356>

In [45]:
y_true = tf.constant([1.])
y_pred = tf.constant([0.9])

In [46]:
loss(y_true, y_pred)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.03512018], dtype=float32)>

In [79]:
y_true = tf.constant([0., 1.,1., 1.])
y_pred = tf.constant([0.99,.1,.2,.25])

In [80]:
loss = custom_loss(3)

In [83]:
loss(y_true, y_pred)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([4.605171  , 0.7675284 , 0.53647935, 0.46209812], dtype=float32)>

In [86]:
import numpy as np

In [87]:
ll=[]

In [88]:
l =np.where(y_true == 1)[0]

In [90]:
ll.append(l)

In [91]:
ll.append(l)

In [95]:
np.array(ll)

array([[1, 2, 3],
       [1, 2, 3]])

In [97]:
np.ndarray.flatten(np.array(ll))

array([1, 2, 3, 1, 2, 3])